### ISSUE TITLE
Not existing interpreter in the template

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [ome/ansible-role-postgresql-backup#3]
Hello!
By default `/usr/bin/bash` doesn't exist, why is it the interpreter hardcoded in the template? Shouldn't it be `/bin/bash` or `/usr/bin/env bash`?

This requires me to modify the file on every machine I'm using this playbook.

Thanks for any explanation.

https://github.com/ome/ansible-role-postgresql-backup/blob/bfce3c0e924db1d4aff97585132948b94f3a96fa/templates/etc-crond-postgresql-backup.j2#L1

**Comment by joshmoore** [comment]
I assume this is just an oversight. We do try to have `/usr/bin/env bash` everywhere. If you'd like to expedite this, feel free to open a PR which will get automatically tested.

cc: @manics
